### ISSUE TITLE
Connection recovery not working as expected

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-perf-test#106]
See the `README` [at this link](https://gist.github.com/lukebakken/39f786477d87b7dff6466b33461262af#file-readme-md). That gist contains a script that will reproduce the issue.

For what it's worth, this Python script does reconnect successfully so I'm pretty sure this isn't due to using `toxiproxy` - [pubsub.py.txt](https://github.com/rabbitmq/rabbitmq-perf-test/files/2203651/pubsub.py.txt)

**Comment by acogoluegnes** [comment]
I reproduced with and without Toxiproxy, even with consumer-only runs and the consumers don't even restart automatically, so there's definitely something to do here. PerfTest hasn't been much tested with regard to automatic connection recovery, I guess it's time to work on it.

**Comment by acogoluegnes** [comment]
I confirm it behaves the same without Toxiproxy (same Java exception, same `{handshake_timeout,frame_header}` error in the server log. Launched PerfTest with `-r 10` (to reduce the publishing rate) and used `rabbitmqctl stop_app/start_app`.

**Comment by lukebakken** [comment]
Thanks everyone!
