### ISSUE TITLE
Cannot specify payload with PerfTestMulti. Only possible with PerfTest

### ISSUE THREAD

**Issue by Qsler** [rabbitmq/rabbitmq-perf-test#132]
With "PerfTest" I can specify my payload:

> bin/runjava com.rabbitmq.perf.PerfTest --body payload.txt

Unfortunately it is not possible with "PerfTestMulti". It would be nice if there was a paramter "body" in the spec.js to specify the payload.

> [
>         {
>                 'name': 'consume',
>                 'type': 'simple',
>                 'body': 'payload.txt',
>                 'uri': 'example',
>                 'params':[
>                 {
>                         'queue-names': ['example'],
>                         'producer-msg-count': 16,
>                         'producer-count': 1,
>                         'consumer-count': 0
>                 }]
>         }
> ]

**Comment by acogoluegnes** [comment]
@Qsler OK, this is fixed. Could you please try with the following snapshot? https://bintray.com/rabbitmq/java-tools-dev/perf-test/2.6.0-SNAPSHOT-20190128-094716#files/perf-test/2.6.0-SNAPSHOT-20190128-094716

E.g.: `bin/runjava com.rabbitmq.perf.PerfTestMulti publish-consume-spec.js publish-consume-result.js`

With `publish-consume-spec.js`:

```json
[{'name': 'benchmark', 'type': 'simple', 'params':
[{'time-limit': 10, 'producer-count': 1, 'consumer-count': 1, 'rate': 10, 'consumer-rate': 5,
  'flags': ['persistent'], 'auto-delete': false,
  'body': ['file1.json', 'file2.json'], 'body-content-type':'application/json'}]}]
```
Don't forget to create 2 `file1.json` `file2.json` files in the working directory.

Thanks!

**Comment by hxk1633** [comment]
> @Qsler OK, this is fixed. Could you please try with the following snapshot? https://bintray.com/rabbitmq/java-tools-dev/perf-test/2.6.0-SNAPSHOT-20190128-094716#files/perf-test/2.6.0-SNAPSHOT-20190128-094716
> 
> E.g.: `bin/runjava com.rabbitmq.perf.PerfTestMulti publish-consume-spec.js publish-consume-result.js`
> 
> With `publish-consume-spec.js`:
> 
> ```json
> [{"name": "benchmark", "type": "simple", "params":
> [{"time-limit": 10, "producer-count": 1, "consumer-count": 1, "rate": 10, "consumer-rate": 5,
>   "flags": ["persistent"], "auto-delete": false,
>   "body": ["file1.json", "file2.json"], "body-content-type":"application/json"}]}]
> ```
> 
> Don't forget to create 2 `file1.json` `file2.json` files in the working directory.
> 
> Thanks!

How would this work with docker containers? And what do you mean by the working directory? Inside the bin folder?

**Comment by michaelklishin** [comment]
Your current working directory in the shell, see `pwd`. If you run PerfTest programmatically, the runner process has a current working directory you can retrieve using `System.getProperty("user.dir")` or, in latest JDK versions, from the default filesystem.
