### ISSUE TITLE
Version mismatch when connecting

### ISSUE THREAD

**Issue by klumhru** [rabbitmq/rabbitmq-perf-test#139]
We're attempting to connect to our Kubernetes based rabbitmq cluster and getting connection errors.

PerfTest version: 2.6.0
Java version: OpenJDK Runtime Environment (build 1.8.0_191-b12)
RabbitMQ version: 3.7.12 using helm chart stable/rabbitmq-ha
Command run: bin/runjava com.rabbitmq.perf.PerfTest --uri amqps://foo:bar@rabbitmq/raz
Output: AMQP protocol version mismatch; we are version 0-9-1, server sent signature 0,0,9,1

I've also tried versions 2.2, 2.4 with the same result. Is there a way I can bypass this or specify an expected version signature or format?

**Comment by michaelklishin** [comment]
`0,0,9,1` does mean -0-9-1 on the wire. This tool uses a Java client version that implements that version (it's been the case since 2011 or so). There were no changes to the protocol or protocol preamble handling in many years, so this is very weird.

Please post a [traffic capture](https://www.rabbitmq.com/amqp-wireshark.html) and `rabbitmq report` output of the target node.

**Comment by michaelklishin** [comment]
Our team uses PerfTest outside of Kubernetes but @gerhard used both on Kubernetes just last week. I don't have a hypothesis at the moment.

**Comment by michaelklishin** [comment]
I'd deploy a couple of [executable tutorials](https://github.com/rabbitmq/rabbitmq-tutorials) to compare. They all implement 0-9-1 these days (but 0-8 and 0-9 are also still supported by RabbitMQ 2.0+).

**Comment by gerhard** [comment]
I ran out of time today, but will check this out first thing tomorrow.

**Comment by gerhard** [comment]
Given this K8S cluster:
```
NAME                                                STATUS   ROLES    AGE   VERSION         INTERNAL-IP   EXTERNAL-IP      OS-IMAGE                             KERNEL-VERSION   CONTAINER-RUNTIME
gke-gerhard-2019-02-25-default-pool-101a62df-57lj   Ready    <none>   1d    v1.11.7-gke.4   10.25.24.12   35.204.207.131   Container-Optimized OS from Google   4.14.89+         docker://17.3.2
gke-gerhard-2019-02-25-default-pool-101a62df-hgh6   Ready    <none>   12h   v1.11.7-gke.4   10.25.24.13   35.204.235.247   Container-Optimized OS from Google   4.14.89+         docker://17.3.2
gke-gerhard-2019-02-25-default-pool-101a62df-mxb8   Ready    <none>   2d    v1.11.7-gke.4   10.25.24.11   35.204.129.241   Container-Optimized OS from Google   4.14.89+         docker://17.3.2
```

And a vanilla rabbitmq-ha:
```
helm install stable/rabbitmq-ha

kubectl get sts/full-grasshopper-rabbitmq-ha
NAME                           DESIRED   CURRENT   AGE
full-grasshopper-rabbitmq-ha   3         3         4m
```

And the following PerfTest deployment:
```
cat <<EOF | kubectl create -f -
> apiVersion: apps/v1
> kind: Deployment
> metadata:
>   labels:
>     app: perf-test
>   name: perf-test
> spec:
>   replicas: 1
>   selector:
>     matchLabels:
>       app: perf-test
>   template:
>     metadata:
>       labels:
>         app: perf-test
>     spec:
>       containers:
>         - image: pivotalrabbitmq/perf-test
>           imagePullPolicy: Always
>           name: perf-test
>           # The URL structure is described here: https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#a-records
>           args:
>             [
>               "--uri",
>               "amqp://guest:$(kubectl get secret full-grasshopper-rabbitmq-ha -o jsonpath="{.data.rabbitmq-password}" | base64 --decode)@full-grasshopper-rabbitmq-ha.default.svc.cluster.local",
>               "--rate",
>               "1",
>             ]
> EOF
deployment.apps/perf-test created
```

I can confirm that PerfTest connects to RabbitMQ successfully:
```
kubectl logs deploy/perf-test
id: test-101417-842, starting consumer #0
id: test-101417-842, starting consumer #0, channel #0
id: test-101417-842, starting producer #0
id: test-101417-842, starting producer #0, channel #0
id: test-101417-842, time: 1.296s, sent: 1.5 msg/s, received: 0.77 msg/s, min/median/75th/95th/99th consumer latency: 7364/7364/7364/7364/7364 µs
id: test-101417-842, time: 2.296s, sent: 1.0 msg/s, received: 2.0 msg/s, min/median/75th/95th/99th consumer latency: 1511/1511/2169/2169/2169 µs
```

I can see that you are using amqps, so I assume that your connection errors are related to SSL. Can you retry connecting PerfTest to RabbitMQ without SSL?

If PerfTest works without SSL, this guide will help: [TLS Support -RabbitMQ](http://www.rabbitmq.com/ssl.html)

**Comment by klumhru** [comment]
@gerhard 
Yeah, I can run perf test on an amqp port, but ssl is not working. As our clients can connect fine to the TLS terminated ELB, and perf-test runs fine on the non-ssl port, this resolves the issue as far as we're concerned. Thanks all.
