### ISSUE TITLE
ArrayIndexOutOfBoundsException when running multiple channels with timeout

### ISSUE THREAD

**Issue by oneiros-de** [rabbitmq/rabbitmq-perf-test#17]
When I start multiple channels with a timeout like this
`bin/runjava com.rabbitmq.perf.PerfTest -z 5 -x 3 -y 3 -X 3 -Y 3`
this will lead to an ArrayIndexOutOfBoundsException when the time is up:

```
id: martin-rabbit-test, time: 5.001s, sent: 6107 msg/s, confirmed: 6106 msg/s, nacked: 0 msg/s, received: 6107 msg/s, min/avg/max latency: 1041/2812/28202 microseconds
Main thread caught exception: java.lang.ArrayIndexOutOfBoundsException: 3
java.lang.ArrayIndexOutOfBoundsException: 3
        at com.rabbitmq.perf.MulticastSet.run(MulticastSet.java:113)
        at com.rabbitmq.perf.PerfTest.main(PerfTest.java:122)

```

**Comment by michaelklishin** [comment]
What's the version used?

**Comment by oneiros-de** [comment]
1.1.0

**Comment by oneiros-de** [comment]
1.1.0

**Comment by acogoluegnes** [comment]
Fixed. @oneiros-de Could you confirm you were also using the `-C` and `-D` options?

**Comment by oneiros-de** [comment]
Nope, we where not using `-C` or `-D`. It happens with a simple `-z 5 -c 2  -d martin-rabbit-test -u martin-rabbit-test -x 2 -y 2 -X 2 -Y 2` on a machine with four vCores - but not always - or it will simply hang.

**Comment by acogoluegnes** [comment]
@oneiros-de Could you build and try with master? Thanks.
