### ISSUE TITLE
Unable to specify exchange's arg 

### ISSUE THREAD

**Issue by junnyea** [rabbitmq/rabbitmq-perf-test#189]
Unable to specify exchange argument for performance testing as the args option for exchange is not available. 
runjava com.rabbitmq.perf.PerfTest --help

why there are args option for queue and message but not for exchange?
-qa,--queue-args <arg>
-mp,--message-properties <arg>

Unable to proceed to test on exchange with durable=true
Caused by: com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=406, reply-text=PRECONDITION_FAILED - inequivalent arg 'durable' for exchange 'test-exchange' in vhost '/': received 'false' but current is 'true', class-id=40, method-id=10)

**Comment by michaelklishin** [comment]
There is `--predeclared`:

```
bin/runjava com.rabbitmq.perf.PerfTest --predeclared -x 1 --exchange "amq.fanout"
```

which should skip most if not all topology declaration.

Please post your further questions to rabbitmq-users, the mailing list, and specify PerfTest version used and what flags you are trying.

**Comment by michaelklishin** [comment]
I don't think there's a big idea behind not having a way to specify exchange properties. Not enough people have asked for it and `--predeclared` is sufficient in the vast majority of cases where you want to use an existing topology with PerfTest. That said, this is open source software, so you are welcome to contribute what you find missing. We can't guarantee to include every feature but scratching your own itch is the spirit of open source.

**Comment by junnyea** [comment]
Thank you for your hint. 
I missed out this `--predeclared` for existing object.
