### ISSUE TITLE
Add option to vary publishing rate

### ISSUE THREAD

**Issue by gerhard** [rabbitmq/rabbitmq-perf-test#192]
It would be helpful to have the option of specifying a variable publishing rate, e.g.

```
bin/runjava com.rabbitmq.perf.PerfTest --variable-rate 1:10 --variable-rate 500:1
# each publisher will publish 1 msg/s for 10 seconds, then 500 msg/s for 1 second, then repeat this cycle ad infinitum
```

The thinking is `--variable-rate [RATE]:[DURATION]`, and the flag can be repeated same way as [docker's `--tag`](https://docs.docker.com/engine/reference/commandline/build/#tag-an-image--t) or [curl's `--header`](https://curl.haxx.se/docs/manpage.html#-H).

The goal is to simulate incoming message bursts. Message backlogs could be simulated in combination with `--consumer-latency`.

**Comment by gerhard** [comment]
Any thoughts @acogoluegnes ?

**Comment by acogoluegnes** [comment]
@gerhard LGTM. Hoping to work on this this week.
