### ISSUE TITLE
Add option to consume messages via basic.get

### ISSUE THREAD

**Issue by gerhard** [rabbitmq/rabbitmq-perf-test#196]
It's not possible currently to consume messages via basic.get. The goal is to simulate with PerfTest:

- [ ] get auto ack
- [ ] get manual ack
- [ ] get empty

![image](https://user-images.githubusercontent.com/3342/56755078-91bef400-6786-11e9-8606-f5f159640517.png)

**Comment by michaelklishin** [comment]
Honestly, I think this feature doesn't belong in PerfTest. Use a small app for that. This is not a feature that we'd like to encourage RabbitMQ users to use.

**Comment by gerhard** [comment]
As much as we discourage the use of `basic.get`, users still use it and get burned by, sometimes  without even knowing - https://github.com/rabbitmq/rabbitmq-server/pull/1701. Adding this feature to PerfTest would allow us to simulate what happens when users do what we discourage them to do - which let's be honest, happens all the time.

Suppose we benchmark this via a small app (btw, we've been there before with lre-apps). How likely is for a regular RabbitMQ user to use this small app to benchmark their RabbitMQ? If PerfTest has this capability, it's easy to imagine a world where we provide _profiles_ for various scenarios than anyone can use against their RabbitMQ. Then we can do this RabbitMQ 3.8.0 node maxes out at **N** `basic.get` requests per second, while the baseline is **M** `basic.get` requests per second - both benchmarked with PerfTest v2.9.0

If you are suggesting that we should drop `basic.get` support in RabbitMQ, happy to drop this too 🤭

**Comment by michaelklishin** [comment]
We should not make `basic.get` a first class feature because it is not really the case. It's polling which has widely understood downsides. We cannot remove it because it's a part of the original protocol and has been available for over a decade. Nonetheless no one should benchmark using `basic.get` because no one should consider polling to be even decently performant.

PerfTest has over 60 options and different ways of operation. `basic.get` is one thing it can do without.

**Comment by lukebakken** [comment]
It might be nice to have a way to dig deeper into [something like this](https://www.pivotaltracker.com/story/show/159998623) without having to write a custom app. PerfTest could always print a warning that `basic.get` should not be used, that sort of thing.

**Comment by gerhard** [comment]
I understand that basic.get is one of the sharper edges of RabbotMQ. To drive this point, we should make it easy to demonstrate what happens when clients use it. If developers can test this method before writing any production code, it will be reassuring to know that we provided the necessary tooling to understand the downsides of this approach. Let's make it easy and obvious via graphs and screenshots, we all know how far documentation has taken us with this.

**Comment by gerhard** [comment]
Do we have everything we need here to disagree and commit? https://en.wikipedia.org/wiki/Disagree_and_commit

**Comment by michaelklishin** [comment]
@dumbbell @acogoluegnes @hairyhum and I discussed this and the conclusion is that seeing how awful `basic.get`/polling performance is compared to having a long lasting subscription (or few) might reduce `basic.get` usage we see in the wild. We believe there should be two arguments:

 * `--polling-consumers` to consume with `basic.get`
 * `--polling-interval` to poll/fetch wit ha delay between iterations (could be `0` for a tight loop)

@gerhard @lukebakken thoughts?

**Comment by gerhard** [comment]
@michaelklishin love it!

Would the current `--autoack` flag control ack-ing in the context of `basic.get` requests?

**Comment by michaelklishin** [comment]
Yes, `basic.get` supports the same acknowledgement modes as regular consumers.

**Comment by michaelklishin** [comment]
One thing I am not sure about is whether we should support both `--polling-consumers <m>` and `--consumers <n>` or should `--polling-consumers` be a boolean flag that means all consumers started are polling. I think the latter is much simpler and would suffice for most cases where you have to use `basic.get` with PerfTest.

**Comment by gerhard** [comment]
> `--polling-consumers` a boolean flag that means all consumers started are polling

This sounds reasonable. I would go one step further in this direction and suggest just `--polling`

**Comment by acogoluegnes** [comment]
`--pooling` and `--polling-interval` (in milliseconds I guess) look good to me.
