### ISSUE TITLE
Add option to nack messages

### ISSUE THREAD

**Issue by gerhard** [rabbitmq/rabbitmq-perf-test#198]
In order to simulate toxic consumers, it would be helpful to have an option that would nack messages, e.g. `--nack true`. If we run multiple consumers, we can have a subset of them nack-ing messages while others ack-ing.

The goal is to use this in demo-ing variation in redelivered messages:

![image](https://user-images.githubusercontent.com/3342/56756065-d9467f80-6788-11e9-976a-d5c104fb1f20.png)

Multiple nacks are out of scope.

**Comment by michaelklishin** [comment]
We should nack with a certain probability. Nacking every message is an extreme scenario that may be worth testing with but it would make the option a lot less useful.

**Comment by gerhard** [comment]
If we nack after `consumer_latency`, then we could have a consumer than nacks messages slowly but continuously. Same for `consumer_rate`. Continuous fast nacks are definitely a problem, but still worth simulating, as we've seen in https://github.com/rabbitmq/rabbitmq-server/pull/1302

**Comment by acogoluegnes** [comment]
> If we run multiple consumers, we can have a subset of them nack-ing messages while others ack-ing.

@gerhard You mean by running several instances of PerfTest? The way I understand the `--nack true` option is that all the consumers of the instance are nacking.

**Comment by gerhard** [comment]
Yes, several instances of PerfTest. 1 PerfTest with `--consumers 1` that nacks after latency expires and a separate PerfTest instance with 1 or more consumers that ack messages.
