### ISSUE TITLE
"Address family not supported by protocol" error with native binary

### ISSUE THREAD

**Issue by acogoluegnes** [rabbitmq/rabbitmq-perf-test#208]
https://groups.google.com/forum/#!msg/rabbitmq-users/vBM9FG4qKXI/SSXWcEMiBQAJ

**Comment by gerhard** [comment]
I've just hit this with [rabbitmq-perf-test-2.9.0-rc.1](https://github.com/rabbitmq/rabbitmq-perf-test/releases/tag/v2.9.0.RC1) running on `Ubuntu 16.04.6 LTS`. Back to the Java version for now.
