### ISSUE TITLE
"auto-ack" is not working properly with com.rabbitmq.perf.PerfTestMulti

### ISSUE THREAD

**Issue by qshao-pivotal** [rabbitmq/rabbitmq-perf-test#21]
```
[{'name':      'consume',
  'type':      'simple',
  'params':    [{'time-limit':     30,
                 'producer-count': 4,
                 'consumer-count': 2,
                 'auto-ack':false}]}]
```
When I try to run with the scenario above, the messages are actually delivered to consumers with ack. When I set autoAck to true, messages are delivered with noack.

perf-test version: 1.2.0
RMQ version 3.6.6

**Comment by michaelklishin** [comment]
`auto-ack` set to `false` means the [manual acknowledgement mode](http://www.rabbitmq.com/confirms.html) will be used. So either this works as expected or there's a misunderstanding of some kind. I suggest that you take it to rabbitmq-users.

**Comment by AzureQ** [comment]
so auto-ack set to true means "actually no ack"?

**Comment by michaelklishin** [comment]
@AzureQ "auto-ack" means "automatic acknowledgement mode". Per your report,

> When I try to run with the scenario above, the messages are actually delivered to consumers with ack

and you have `auto-ack` set to `false`, which means "manual acknowledgement mode."

Unfortunately in the protocol the field says "no ack", which definitely adds to the confusion.

**Comment by AzureQ** [comment]
Got it. Thanks a lot!
