### ISSUE TITLE
Not specifying queue names improperly handled

### ISSUE THREAD

**Issue by danehammer** [rabbitmq/rabbitmq-perf-test#22]
It looks like the code allows you to pass in an empty list for queue names but looking at `com.rabbitmq.perf.PerfTest` it would appear the code actually expects the "empty list" to be a list with an empty string in it.

Here: https://github.com/rabbitmq/rabbitmq-perf-test/blob/v1.2.0/src/main/java/com/rabbitmq/perf/MulticastParams.java#L239

This fails on Java 7 and 8 with an UnsupportedOperationException when calling `AbstractList#add(Object)` when `MultiCastParams#queueNames` is set to an empty list (or an NPE if you provide `null`). But behaves as expected if you set queueNames to a list with an element of `""`, which passes over the linked `if` branch.

**Comment by michaelklishin** [comment]
An empty string means "the server should generate a vhost-unique name" in the protocol. So an empty list does make much sense but a list with a single empty string does. Sorry but looks like this works as expected?

**Comment by michaelklishin** [comment]
@acogoluegnes can I be missing something here?

**Comment by acogoluegnes** [comment]
@michaelklishin Yes, it works as expected, at least from the command line. But if for some reason the list is empty and doesn't support the `add()` method, there would be an error. I changed the setter to more defensive, by creating a copy of the passed-in list.

**Comment by michaelklishin** [comment]
Thank you, @acogoluegnes.

**Comment by danehammer** [comment]
Thanks!
