### ISSUE TITLE
When using multiple URIs and defining multiple queues, spread queue declarations across all nodes

### ISSUE THREAD

**Issue by gerhard** [rabbitmq/rabbitmq-perf-test#221]
Given the following PerfTest options:

```
--producers 100 --rate 1 --confirm 100
--queue-pattern 'qq%d' --queue-pattern-from 1 --queue-pattern-to 10
  --auto-delete false --queue-args x-queue-type=quorum
--flag persistent
--consumers 20 --qos 500
--uris amqp://foo:bar@10.0.0.1,amqp://foo:bar@10.0.0.2,amq://foo:bar@10.0.0.3
```

I  would expect queues to be randomly declared across all 3 nodes in the RabbitMQ cluster. Currently, with PerfTest 2.9.0-rc.2, all queues are declared on a single node, typically the first node.

I would expect this to be the default behaviour, which is what we would recommend as a best practice.

**Comment by michaelklishin** [comment]
If we already connect to all  those URIs instead of using them for recovery only it would make some sense.  Otherwise this would fundamentally be at odds with what the rest of the application does. Also, this is what queue master locators are for.

**Comment by gerhard** [comment]
Yes, we connect to all URIs.

If I understand correctly, there is currently a single connection used for configuration, meaning that all queues will be defined via that connection, on the node that it connects to.

As a temporary stop-gap, I will make use of the queue master locator - all queues are quorum btw.

**Comment by acogoluegnes** [comment]
There's indeed a single connection to deal with resources (this is not always the case, e.g. with exclusive queues). It should be possible to use as many configuration connections as URIs to spread the queues on all the nodes. It should be the default, as this is what we usually recommend. It would also be good not to have to resort to queue master locator, PerfTest should handle this boilerplate by itself.
