### ISSUE TITLE
Connection and topology recovery issue using server-named queues

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-perf-test#247]
This _might_ be just how things are supposed to work. To reproduce:

* Using latest `master` umbrella, start a cluster:
    ```
    make PLUGINS='rabbitmq_management rabbitmq_top' LOG=debug NODES=3 start-cluster
    ```
* Start up PerfTest which will create 10 server-named queues:
    ```
    mvn -q exec:java -Dexec.mainClass='com.rabbitmq.perf.PerfTest' \
      -Dexec.args='--uris amqp://localhost:5672,amqp://localhost:5673,amqp://localhost:5674 --queue-args x-queue-type=quorum --auto-delete false --flag persistent --producers 10 --consumers 10 --rate 128'
    ```
* Stop node `rabbit-3`:
    ```
    (23.0.2)lbakken@shostakovich ~/development/rabbitmq/umbrella/deps/rabbitmq_server_release (master=)
    $ ./sbin/rabbitmqctl -n rabbit-3 shutdown
    ```
* In the management UI, you will notice several new server-named queues created, but they won't have consumers, only publishers (and thus a message backlog begins)
* Re-start node `rabbit-3`. Copy the output of the `start-cluster` command for `rabbit-3` and execute it on its own.
* In the management UI, that node is back but still there are no consumers on certain queues.

If you start PerfTest using `queue-pattern` as described in #221 recovery works correctly:

```
mvn -q exec:java -Dexec.mainClass='com.rabbitmq.perf.PerfTest' -Dexec.args='--uris amqp://localhost:5672,amqp://localhost:5673,amqp://localhost:5674 --queue-args x-queue-type=quorum --auto-delete false --flag persistent --queue-pattern qq%d --queue-pattern-from 0 --queue-pattern-to 9 --producers 10 --consumers 10 --rate 128'
```

This may not be worth (or possible!) to fix.

**Comment by acogoluegnes** [comment]
@lukebakken Thanks for pointing this out and for the steps to reproduce.

PerfTest would re-create server-named queues, whatever the other arguments are. So the idle queues were just leftovers from the connections initially on the failed node.

I changed this: if the queue is still around after the re-connection, the queue is not re-created, we assume the user wants a long-lived server-named queue (sounds weird for a real application).

I pushed a fix to master, you can try it out if you want.

**Comment by lukebakken** [comment]
Fixed! Thanks!
