### ISSUE TITLE
When -y 0 (no consumers) and -p (predeclared entities) are used, server-named queues should not be declared

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-perf-test#25]
Currently when `-y 0` and `-p` are combined to test a consumer application (the idea is to only use PerfTest for publishing), a server-named queue is declared and while it is auto-delete, it never has any consumers => sticks around.

This is confusing and annoying.

Reported by @liwang-pivotal.

Perhaps a more sensible behavior would be to not "configure" (pre-declare, bind) any queues when `--predeclared` is passed and we have no consumers. I can't currently see any scenarios where the behavior we have right now would be desired.

**Comment by michaelklishin** [comment]
@acogoluegnes I'm happy to revert this if you see any downsides, a customer @liwang-pivotal is working with was pretty annoyed by this so we decided to rush it a bit since it only affects a rare combination of CLI switches :)

**Comment by acogoluegnes** [comment]
@michaelklishin Makes perfect sense to me.
