### ISSUE TITLE
[RFE] Add parameters  to enable SNI

### ISSUE THREAD

**Issue by Gsantomaggio** [rabbitmq/rabbitmq-perf-test#252]
It would be useful to have parameters to enable SNI and set the SNI value on TLS. 

Most of the k8s ingresses support the SNI match to redirect the traffic, see https://github.com/rabbitmq/tgir/pull/20

At the moment to test  https://github.com/rabbitmq/tgir/pull/20 I am using [this test client](https://github.com/Gsantomaggio/rabbitmq-utils/blob/master/examples/client_sni/rabbitmq/src/main/java/gas/App.java#L39-L52)  

cc @gerhard

**Comment by gerhard** [comment]
What do you think @acogoluegnes?

**Comment by acogoluegnes** [comment]
Sure, that's possible. What kind of values do you expect for the server names, nothing fancy? I guess comma-separated values would work.

The only trick is to make it work for both blocking IO (with a `SocketConfigurator`) and NIO (like in the example), with a `SslEngineConfigurator`). This would transparent for the user.

**Comment by Gsantomaggio** [comment]
> I guess comma-separated values would work

Yes, I think so!
