### ISSUE TITLE
Version 2.14 has wrong version in Makefile

### ISSUE THREAD

**Issue by rcousens** [rabbitmq/rabbitmq-perf-test#263]
Hi,

Was building the docker images locally as I needed aarch64 support and noticed the v2.14 tag/release and master currently have the version in the Makefile specified as "2.13.0"

Cheers

**Comment by acogoluegnes** [comment]
CI injects the version with a command line parameter when it builds the Docker image. I can bump the version right now, but it's not guaranteed to be up-to-date all the time.
