### ISSUE TITLE
Support for ARM 64 bits

### ISSUE THREAD

**Issue by rnsc** [rabbitmq/rabbitmq-perf-test#265]
Hello,

I was wondering if adding a Dockerfile to support the ARM64 would be accepted?

Kind regards,

**Comment by michaelklishin** [comment]
Yes, it would. Please submit a PR :) Thank you!

**Comment by rnsc** [comment]
@michaelklishin there you go: https://github.com/rabbitmq/rabbitmq-perf-test/pull/266

Hope it's an ok change, I'd be happy to change it
