### ISSUE TITLE
Feature request: Run as non-privileged user within docker container

### ISSUE THREAD

**Issue by drewhammond** [rabbitmq/rabbitmq-perf-test#271]
Hi,

We have a security requirement that processes cannot run as root within containers. It would be great if the public image could use a non-privileged user (same goes for the new stream-perf-test tool, but I can't find that repo to file an issue).

Thank you!

**Comment by acogoluegnes** [comment]
@drewhammond we pushed a change, can you try the `pivotalrabbitmq/perf-test:dev` Docker image?
