### ISSUE TITLE
Is it possible to declare classic queues as durable?

### ISSUE THREAD

**Issue by RafalGoslawski** [rabbitmq/rabbitmq-perf-test#272]
The [documentation](https://rabbitmq.github.io/rabbitmq-perf-test/stable/htmlsingle/#basic-usage) says
```
PerfTest can use durable queues and persistent messages:

bin/runjava com.rabbitmq.perf.PerfTest -x 1 -y 2 -u "throughput-test-5" --id "test-5" -f persistent
```
There doesn't seem to be any argument to declare queues as durable. Is it possible to declare durable queues without persistent messages?

**Comment by lhoguin** [comment]
Yes, please use `--auto-delete false`.

**Comment by RafalGoslawski** [comment]
Tried that, doesn't seem to work:
```
$ bin/runjava com.rabbitmq.perf.PerfTest -h ${URI} -u test-ad2 -x 1 -y 0 -c 1000 --auto-delete false -C1

id: test-105448-661, starting producer #0
id: test-105448-661, starting producer #0, channel #0
test stopped (Producer reached message limit)
id: test-105448-661, sending rate avg: 2.1 msg/s
id: test-105448-661, receiving rate avg: 0 msg/s
```
The queue doesn't show up as durable in RabbitMQ web interface 
[screenshot](https://imgur.com/a/FNQQJgG)
Am I missing something?

**Comment by michaelklishin** [comment]
RabbitMQ does not use GitHub issues for questions. Use discussions, community Slack or the mailing list.

From [the docs](https://rabbitmq.github.io/rabbitmq-perf-test/stable/htmlsingle/#:~:text=RabbitMQ%20has%20a%20throughput%20testing,HTML%20graphs%20of%20the%20output.):

```
bin/runjava com.rabbitmq.perf.PerfTest -x 1 -y 2 -u "throughput-test-5" --id "test-5" -f persistent
```

<img width="831" alt="Screenshot 2021-08-10 at 14 04 22" src="https://user-images.githubusercontent.com/1090/128856115-171a15ae-4dfb-4b85-a88e-c10188fefc7c.png">

You can always declare any topology you like and publish to any exchange you please with `--predeclared`.

**Comment by michaelklishin** [comment]
```
bin/runjava com.rabbitmq.perf.PerfTest -x 1 -y 2 -u "throughput-test-5" --id "test-5" -f persistent --auto-delete=false
```

results in a non-auto-delete durable queue which will be retained after the PerfTest instance is stopped.

**Comment by lhoguin** [comment]
Thanks, I have double checked and you need both `-f persistent --auto-delete false` indeed.

**Comment by RafalGoslawski** [comment]
Ok, thanks. That confirms there's currently no way to have durable queue _without_ persistent messages.
