### ISSUE TITLE
Feature request: nack(requeue:false)

### ISSUE THREAD

**Issue by RafalGoslawski** [rabbitmq/rabbitmq-perf-test#273]
Hi, I'm tracking a bug related to dead-letter-exchange and nack-ed messages with requeue=false.

Is it possible to add a CLI argument that sets the requeue=flase on nack?

**Comment by michaelklishin** [comment]
[It's not](https://github.com/rabbitmq/rabbitmq-perf-test/blob/503b5bc979423d8fc5aba01dbc19ade110561ae4/src/main/java/com/rabbitmq/perf/Consumer.java#L42) but I guess it could fit in.

Please put together a PR and we'll see if adding this option would potentially have any downsides. Thank you.
