### ISSUE TITLE
Re-implement --rate as --publishing-interval?

### ISSUE THREAD

**Issue by mkuratczyk** [rabbitmq/rabbitmq-perf-test#289]
Conceptually, `--rate` and `--publishing-interval` do basically the same thing. However, their implementation is very different. [We already know](https://github.com/rabbitmq/rabbitmq-perf-test/issues/287) that `--publishing-interval` uses less resources. Now we also see that it provides much more accurate data with many publishers. I have these two perf-test instances running:

```
./perf-test_linux_x86_64 -x 350 -X 40 -y 0 -s 1024 -u stream1 --queue-args x-queue-type=stream --use-millis -c 1 -P 1

./perf-test_linux_x86_64 -x 350 -X 40 -y 0 -s 1024 -u stream1 --queue-args x-queue-type=stream --use-millis -c 1 -r 1
```

As you can see, they publish to the same stream over AMQP and the only difference is `-r` vs `-P`. They both should publish 14000 messages a second. However, the actual results look very different. From `-r 1`:
```
id: test-114815-606, time: 979.983s, sent: 3592 msg/s, confirmed: 3665 msg/s, nacked: 0 msg/s, min/median/75th/95th/99th confirm latency: 1/3567/5354/7358/8727 ms
```
From `-P 1` (at the same time):
```
id: test-110958-502, time: 3292.584s, sent: 14000 msg/s, confirmed: 14000 msg/s, nacked: 0 msg/s, min/median/75th/95th/99th confirm latency: 1/36/47/65/70 ms
```

Due to the `-r` implementation, it seems like perf-test cannot actually publish all the 14000 messages every second. That seems to lead to an artificially inflated publish latency - it reports 5-9 seconds latency, even though there is no server-side problem, as evidenced by the `-P 1` instance, which happily publishes 14000 msg/s with low latency to the same stream at the same time.

Is there any case where `-r` is better? Given that the vast majority of users use `-r`, I think it's worth changing it so that it behaves like `-P` and provides more stable publish rates and more accurate latency.

**Comment by acogoluegnes** [comment]
With `--rate` a publisher is a thread with a `while(true)` loop and `Thread.sleep` to reach the appropriate rate. With `--publishing-interval` a publisher is a method called periodically by a shared thread.

`--rate` should be more accurate and even just possible for larger rates (maybe 100s or 1000s) than `--publishing-rate`, _for one publisher_.

Well, I haven't measured, so it's just a guess actually. Let's say `--rate` should work better when we reach the limit of the scheduling used by `--publishing-rate`.

A good rule of thumb is:
* high individual rate, small number of publishers: use `--rate`
* low individual rate (< 10 messages / second), large number of publishers: use `--publishing-interval`

In your tests above (1 message / second, 350 publishers), it is no surprise that `--publishing-interval` works better, it has been designed for these conditions. The `--rate` mode has 350 more threads to deal with, and they are most of the time sleeping.

I don't think we can re-implement `--rate` as `--publishing-interval` but I have a couple of suggestions:
* revise the `--rate` limitation implementation. It's custom, I haven't really looked into it, we could try a ready-to-use implementation, like [Stream PerfTest does](https://github.com/rabbitmq/rabbitmq-stream-java-client/blob/d1fb6130a9afe33d7983d71d9281f73eefb0e137/src/main/java/com/rabbitmq/stream/perf/StreamPerfTest.java#L655).
* use the `--publishing-interval` mode (scheduling publishing) for low `--rates`(< 10 messages / second). That's a usability trick and it could make PerfTest more reliable "automatically" for cases like the one above.

**Comment by mkuratczyk** [comment]
Thanks, these suggestions sound great. I'd be totally ok with just switching to the mode more appropriate for the configuration but that's up to you of course.

**Comment by acogoluegnes** [comment]
Well it makes sense to internally turn `--rate 10` into `--publishing-interval 0.1` even for one publisher, but we won't be able to completely replace one argument by the other, because there's no single argument that can easily replace `1000 messages / second` and `1 message every 10 minutes`. Having one unity to support both would require ridiculously long numbers or a complicated syntax.

**Comment by acogoluegnes** [comment]
> turn `--rate 10` into `--publishing-interval 0.1`

@mkuratczyk @kjnilsson Do you consider this a breaking change? I don't personally, it should just make these low-rate runs more accurate at worse.

**Comment by mkuratczyk** [comment]
In my opinion it's more of a bugfix than a breaking change. Having perf-test report 8 seconds publisher confirm latency, when there is no server-side problem is very confusing.

I'm not sure what the specific threshold should be - I can run some tests if you want.

**Comment by acogoluegnes** [comment]
The threshold would be 10 messages / second right now, because with #287 the "lower" publishing rate is 0.1 (= publishing a message every 0.1 second). This is arbitrary though.

**Comment by mkuratczyk** [comment]
Sounds good!

**Comment by acogoluegnes** [comment]
@mkuratczyk BTW when experimenting I would recommend using the Java binary if possible. The native binary uses GraalVM runtime, which I'm not familiar with. The Java binary running on a regular JRE should make our life easier when investigating such cases.

**Comment by acogoluegnes** [comment]
About the rate limiter implementation, we may have to stick to the existing one, which supports variable rates. The rate limiter implementations I know (Guava, resilience4j) do not support variable rates.

**Comment by mkuratczyk** [comment]
Noted. I just rechecked with a regular JAR/JRE to see the impact of GraalVM and it might be better but still nowhere near the smoothness of `-P`. GraalVM seems to jump to a high latency and stay there, while regular JRE seems to fluctuate initially with spikes even worse than the native binary (over 20 seconds latency here and there) but after about a minute it settles down with ~200ms and the expected 14k publish rate more or less.
