### ISSUE TITLE
Deleting a queue in use results in repetead channel exceptions

### ISSUE THREAD

**Issue by Zerpet** [rabbitmq/rabbitmq-perf-test#378]
By deleting a queue in use by a perf-test run, we trigger repead channel exceptions with message `no queue 'A' in vhost 'Z'`. The queue is not re-declared and message consumption stops.

**Repro:**
- Run perf test with these flags: `--rate 100 --queue snafu --exchange test -f persistent -ad false`
- Wait for perf-test to start producing/consuming
- Delete the queue "snafu" via management UI or `rabbitmqctl`

The following errors are observed in RabbitMQ Server:

```
2022-09-06 16:45:23.078110+00:00 [error] <0.1623.0> Channel error on connection <0.1255.0> (10.4.1.23:42654 -> 10.4.1.20:5672, vhost: '/', user: 'guest'), channel 2:
2022-09-06 16:45:23.078110+00:00 [error] <0.1623.0> operation queue.declare caused a channel exception not_found: no queue 'snafu' in vhost '/'
2022-09-06 16:45:28.101597+00:00 [error] <0.1630.0> Channel error on connection <0.1255.0> (10.4.1.23:42654 -> 10.4.1.20:5672, vhost: '/', user: 'guest'), channel 2:
2022-09-06 16:45:28.101597+00:00 [error] <0.1630.0> operation queue.declare caused a channel exception not_found: no queue 'snafu' in vhost '/'
```

Perf-test detects the consumer cancelled:

```
id: test-163455-131, time: 627.220s, sent: 100 msg/s, received: 99 msg/s, min/median/75th/95th/99th consumer latency: 483/1832/2081/2419/12396 µs
Consumer cancelled by broker for tag: amq.ctag-YzpmP3yv-M4Ytg4WmjEzggid: test-163455-131, time: 628.222s, sent: 99 msg/s, received: 61 msg/s, min/median/75th/95th/99th consumer latency: 458/726/792/1282/3282 µs
id: test-163455-131, time: 629.222s, sent: 100 msg/s, received: 0 msg/s, min/median/75th/95th/99th consumer latency: 0/0/0/0/0 µs
id: test-163455-131, time: 630.222s, sent: 100 msg/s, received: 0 msg/s, min/median/75th/95th/99th consumer latency: 0/0/0/0/0 µs
```

**Expected behaviour:** perf-test declares the queue and resumes message consumption

**Comment by Zerpet** [comment]
@acogoluegnes I'd like to give this a go, seems like an easy first-issue. The root cause seems to be a passive queue declaration somewhere, based on Luke's investigation.

**Comment by acogoluegnes** [comment]
Sure, give it a try. I don't guarantee it'd be easy though :-)

PerfTest usually manages to recover from network glitches, but not from changes in the topology. Note the consumer cancellation could also be because the owning node of the queue is down (and the consumer is connected to another node). In this case the consumer won't be able to re-declare the queue. I don't think there's a way to make a difference with a deleted queue. You'll just have to deal with an error when re-declaring the queue.

**Comment by Zerpet** [comment]
I had a working solution for my use case, however, some tests revealed a flaw in my implementation when generated queue names are used e.g. `amq.gen-NsfnZ6V51CR8AeEjhrEyjQ`. In this case, a `channel.queue-declare` causes a channel exception with `access_refused: queue name 'amq.gen-abcd1234' contains reserved prefix 'amq.*'`. I think it is fair to fail in this situation, as in, not recover the topology.

I also noticed that bindings need to be redeclared, alongside with the queue. I feel as if I'm doing a "partial" topology recovery as part of the `handleCancel()` handler. I'll send a draf PR soon-ish before I start going down the rabbit hole 🥕
