### ISSUE TITLE
Uber JAR affects `perftest_args` metric

### ISSUE THREAD

**Issue by mkuratczyk** [rabbitmq/rabbitmq-perf-test#379]
A small usability regression in 2.19. After switching to an uber JAR, `perftest_args` metric contains `bin/runjava com.rabbitmq.perf.PerfTest`, which is not very useful.

```
$ curl -s localhost:8080/metrics | grep ^perftest_args
perftest_args{command_line="bin/runjava com.rabbitmq.perf.PerfTest -x 2 -y 0 ...} 1.0
```

**Comment by acogoluegnes** [comment]
I can't reproduce, how did you come up with this result?

**Comment by mkuratczyk** [comment]
I noticed this when I moved to `pivotalrabbitmq/perf-test:dev-2.19` image from the `:latest` one. Perhaps this is docker image specific? I'll check, maybe I did something strange

**Comment by acogoluegnes** [comment]
May be the Docker image, I haven't checked with it.

**Comment by mkuratczyk** [comment]
Sorry, totally my fault. I messed up adopting my Kubernetes deployment template to the new way of starting perf-test.

**Comment by acogoluegnes** [comment]
Sounds good. I could not reproduce with the Docker image either:

```
docker run -it --rm --network host pivotalrabbitmq/perf-test:dev-2.19 --rate 100 -mpr -mcla
```
