### ISSUE TITLE
Running a publisher-only perf test with predeclared queue

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-perf-test#43]
Here's my scenario -

* Start up RabbitMQ from the `stable` branch of the umbrella project
* Create a durable queue named `gh-1388`
* Start up PerfTest using the `master` branch like so:
    ```
    mvn -q exec:java -Dexec.mainClass=com.rabbitmq.perf.PerfTest -Dexec.args="-y0 -p -u gh-1388 -s 512"
    ```

At this point I can see Publish numbers going up on the Overview page in the management UI, but nothing is routed to `gh-1388` like I would expect.

I've tried running the same arguments to publish a set of messages as shown in [this document](https://www.rabbitmq.com/java-tools.html) but I see the same result ... nothing is routed to the `throughput-test-14` queue:

```
-y0 -p -u "throughput-test-14" -s 1000 -C 1000000 --id "test-14" -f persistent
```

If I bind queue `gh-1388` to the `amq.direct` echange via the UI, I can publish to it using these arguments:

```
--consumers 0 --producers 1 --predeclared --queue gh-1388 --exchange amq.direct --routingKey gh-1388
```

**Comment by michaelklishin** [comment]
`--predeclared` by definition assumes you set your topology up out of band, any way the user likes. We can make publishers declare the queue but that's a little odd.

**Comment by lukebakken** [comment]
I do think something has changed since the example given [in the docs](https://www.rabbitmq.com/java-tools.html) (`throughput-test-14` / "pre-populate a queue") implies that using `--predeclared` and `--queue` should be all you need to do to use a pre-existing queue.

**Comment by michaelklishin** [comment]
Hm, yes, my reading matches yours.

**Comment by lukebakken** [comment]
I'll see if I can figure it out tomorrow unless @acogoluegnes beats me to it 😃

**Comment by acogoluegnes** [comment]
I tried with a57ed36 (just after the initial import from the Java Client) and the `-y0 -p -u "throughput-test-14" -s 1000 -C 1000000 --id "test-14" -f persistent` declares the queue, so it's a regression. More digging.

**Comment by acogoluegnes** [comment]
It was introduced [between 1.2.0 and 1.3.0](https://github.com/rabbitmq/rabbitmq-perf-test/compare/v1.2.0...rabbitmq:v1.3.0), [here](https://github.com/rabbitmq/rabbitmq-perf-test/compare/v1.2.0...rabbitmq:v1.3.0#diff-714cc2f6275d1d4d3c8f65aa8a9d5164L229).

**Comment by acogoluegnes** [comment]
I don't know how to reproduce #25 actually: as soon as `--predeclared` is used, queues are not created (they're bound though). I'd vote to reverse #25.

**Comment by lukebakken** [comment]
@acogoluegnes here is the most confusing behavior using the current PerfTest code (`master`):

* Start up RMQ and create a durable queue named `throughput-test-14`
* Start up PerfTest with these arguments:
    ```
    -y0 -p -u "throughput-test-14" -s 1000 -C 1000000 --id "test-14" -f persistent
    ```

I don't expect the queue to be created since I'm using the `-p` argument, but I do expect messages to be published using the default exchange with a routing key of `throughput-test-14` so that they end up in the `throughput-test-14` queue.

However, I'm not seeing this happen - when I run that command, the messages aren't routed so I assume they are being published without a routing key. What's even more odd is that if I add the `-k throughput-test-14` argument they still aren't routed 🤔

**Comment by acogoluegnes** [comment]
@lukebakken Right now the creation and the binding are in the same Java method. This method isn't called if `-p` is specified. Reverting #25 would make the binding happen.

Nevertheless, a `direct`-named exchange is created and is bound to the queue. I'd rather use the default exchange as you suggested.

**Comment by acogoluegnes** [comment]
Found an argument combination to reproduce #25: using `--predeclared` without specifying any queue. The [auto-generated queue is then created](https://github.com/rabbitmq/rabbitmq-perf-test/blob/53be59ac276c540a84cafb2d2cfd8630f2138333/src/main/java/com/rabbitmq/perf/MulticastParams.java#L278-L280). This was originally introduced in #5 (support for multiple queues). Only reverting #25 isn't enough then.
