### ISSUE TITLE
Support priority flag

### ISSUE THREAD

**Issue by acogoluegnes** [rabbitmq/rabbitmq-perf-test#62]
A follow-up on https://github.com/rabbitmq/rabbitmq-perf-test/pull/15#issuecomment-352826592. The `--flag priority=1` should do the job and avoid introducing a new option.

**Comment by acogoluegnes** [comment]
After a bit of thinking, we should add a `--message-properties` option, just like for queue arguments, as flags are flags, they shouldn't contain any value.

**Comment by michaelklishin** [comment]
I prefer `--message-properties` but would like to see a few examples of various combinations before we implement them. E.g. what would setting a timestamp, a delivery mode (persistence) and a header look like on the command line?

**Comment by acogoluegnes** [comment]
An example with properties:
```
--message-properties userId=foo,priority=10,deliveryMode=2
```

For headers, the simplest would be to add as headers any entry that is not a property:
```
--message-properties userId=foo,timestamp=1514907956
```

At the implementation level, there's a chain of `Function`s that can modify the `AMQP.BasicProperties.Builder` for each message. There's [a case](https://github.com/rabbitmq/rabbitmq-perf-test/pull/63/files#diff-ebdc6760ed8558241d6127b3584a5beeR91) where a timestamp header is added. I think the `--message-properties` option should have the last word and the corresponding builder function should override any value set up before (in this case, a timestamp header).
