### ISSUE TITLE
External environment (e.g. an app server) can unintentionally make PerfTest use TLS

### ISSUE THREAD

**Issue by ramato-procon** [rabbitmq/rabbitmq-perf-test#65]
I've implemented a REST service which internally calls the PerfTest.main() Method.
The application server is running in ssl mode. 
This causes the PerfTest to connect to AMQP with an SSLSocket, even if the URI ("-h" Parameter) starts with: amqp://
(and not with amqps://).
In my opinion this is a wrong behaviour.
I think it is located here:

```
private static SSLContext getSslContextIfNecessary(CommandLine cmd, Properties systemProperties) throws NoSuchAlgorithmException {
        SSLContext sslContext = null;
        if (cmd.hasOption("useDefaultSslContext")) {
            LOGGER.info("Using default SSL context as per command line option");
            sslContext = SSLContext.getDefault();
        }
        for (String propertyName : systemProperties.stringPropertyNames()) {
            if (propertyName != null && isPropertyTlsRelated(propertyName)) {
                LOGGER.info("TLS related system properties detected, using default SSL context");
                sslContext = SSLContext.getDefault();
                break;
            }
        }
        return sslContext;
    }

    private static boolean isPropertyTlsRelated(String propertyName) {
        return propertyName.startsWith("javax.net.ssl") || propertyName.startsWith("jdk.tls");
    }
```

**Comment by michaelklishin** [comment]
@ramato-procon that's an edge case, not a wrong behaviour. We can consider a way to forcefully disable TLS for when PerfTest is used as a library. PerfTest is first and foremost a standalone tool.

@acogoluegnes WDYT?

**Comment by acogoluegnes** [comment]
@michaelklishin Yes, the user should be able to explicitly disable TLS. I don't see how to do so (simply) without adding a new command line option though.

**Comment by ramato-procon** [comment]
@michaelklishin Thank you. As the perf-test is a maven library I assumend it would be fine to use it in an application server.
I also struggled with some other issues (like System.exit on an error), but I'm just using it in a test microservice, so I'm fine with that.

**Comment by michaelklishin** [comment]
@acogoluegnes I think a new flag is OK, could be a public library API setter, too that doesn't get a CLI flag.

**Comment by michaelklishin** [comment]
We don't discourage PerfTest use as a library and would like ot make that easier but since for our team it's a standalone tool, I'm not surprised that issues such as #66 or this one come up. This scenario is not applicable to the standalone tool.

**Comment by acogoluegnes** [comment]
@ramato-procon As a workaround for now, you can mimic what `PerfTest#main` does with `MulticastParams` and `MulticastSet`. This method is quite long but it mainly contains command line logic, so you could easily avoid the pain points met in a library usage.

**Comment by acogoluegnes** [comment]
@ramato-procon Regarding `System#exit`, does [this](https://github.com/rabbitmq/rabbitmq-perf-test/commit/1d7d5a30d4af6f12c2224bcbd2ebf00f8726c723) make your life easier?

**Comment by acogoluegnes** [comment]
@ramato-procon And 904a374 should also make embedding easier.

**Comment by ramato-procon** [comment]
@acogoluegnes perfect, thank you!
