### ISSUE TITLE
Publish Maven artifacts

### ISSUE THREAD

**Issue by johnlonganecker** [rabbitmq/rabbitmq-perf-test#7]
It would be really useful for me to be able to add this as a maven repo in my pom.xml file. I didn't see it on http://mavenrepository.com/. Does it exist elsewhere?

**Comment by michaelklishin** [comment]
No. This is a standalone tool, not a library. Why do you need it to add a dependency?

**Comment by johnlonganecker** [comment]
I found the java library very useful to run performance tests, but I found it would be easier to put a rest api on top of it and have the response go straight into the graphs.

Simple web app I wrote using it.
https://github.com/johnlonganecker/rabbitmq-performance-app

I have to include all these java files in my repo:
https://github.com/johnlonganecker/rabbitmq-performance-app/tree/master/src/main/java/com/rabbitmq/perf

It would be nice to just specify the project in my pom.xml file then not have to commit it all.

**Comment by michaelklishin** [comment]
OK, we can publish it as a Maven artifact.

**Comment by johnlonganecker** [comment]
cool thanks!

**Comment by acogoluegnes** [comment]
It's already in Maven Central: http://mavenrepository.com/artifact/com.rabbitmq/perf-test

But for some reasons, it doesn't show up in the search results.

**Comment by johnlonganecker** [comment]
Thats great, I will just use that. I will submit a PR with a link to that in the README.md file so if anyone else wants to use it they can find it.

**Comment by michaelklishin** [comment]
Thank you!
