### ISSUE TITLE
Add support for exclusive queues

### ISSUE THREAD

**Issue by gerhard** [rabbitmq/rabbitmq-perf-test#76]
I needed to test the behaviour of auto-delete queues that are also exclusive. I was imagining something along the lines of:

```
com.rabbitmq.perf.PerfTest --consumers 2 --producers 1 --rate 1 \
  --queue-pattern perf-test-%d --queue-pattern-from 1 --queue-pattern-to 2 \
  --auto-delete true --exclusive true
```

To result in the following workload:

* 1 producer publishing messages into the `direct` exchange with an empty routing key
* 2 auto-delete & exclusive queues bound to the `direct` exchange: `perf-test-1` & `perf-test-2`
* 1 consumer per queue

Thoughts?

**Comment by acogoluegnes** [comment]
This makes sense only if the producers and the consumers share the same connection. We can add the `--exclusive` option, that would automatically trigger the sharing of the same connection across all the operations of the test (topology configuration, producers, and consumers). Would that be OK?

Regarding the publishing in the example, as [stated in the `--queue-pattern` option documentation](http://www.rabbitmq.com/java-tools.html#working-with-many-queues), the producers are balanced across the queues in a round-robin fashion, so 2 producers would be needed to publish to both queues. Does that make sense?

**Comment by michaelklishin** [comment]
Connection sharing would further complicate an already complex tool and its CLI flag matrix. Exclusive queues make little sense in the context of benchmarks unless a pre-declared topology is used. That's what I'd recommend instead. The entire point of exclusive queues is to limit all operations on them to a single connection and that isn't helpful at all in PerfTest's case.

**Comment by gerhard** [comment]
Agreed, it's logical for the producer to share the same connection with the consumer when the queue is exclusive. I'm also happy if the exclusive queue names are generated by the server.

I understand if you do not want to add this feature to PerfTest. The benchmark makes sense for the customer that I'm helping determine RabbitMQ limitations. To me, it make sense for the official RabbitMQ benchmarking tool, PerfTest, to support this feature. I'm easy either way.

**Comment by acogoluegnes** [comment]
From a previous discussion with @gerhard:

> I need to define many queues that are idle. When PerfTest process stops, even though the queues are auto-delete, they do not get deleted. If the queue is exclusive AND auto-delete, it gets deleted when PerfTest process stops. Also, exclusive and auto-delete queues seem to behave differently from just auto-delete queues.

Sharing the same connection between a consumer and a producer isn't easy (especially considering there can be a different number of consumers and producers). Using the same connection for everyone as soon as a `--exclusive` flag is set up shouldn't be complicated and it looks to me it fits your requirement above. Would that work for you @gerhard?

**Comment by gerhard** [comment]
The workload that we would like to simulate with PerfTest is a typical IoT one:

* 1 producer with 1 connection & 1 channel publishing 1 message every 600 seconds
* 1 consumer with 1 connection &  1 channel defining an exclusive & auto-delete queue which is bound to a topic exchange - all producers publish to this topic exchange

We're currently using Bunny, the Ruby client, to simulate 10,000 producers & 10,000 consumers with 10,000 auto-delete & exclusive queues per RabbitMQ node. The goal is to see how many queues a single node can handle before Mnesia contention becomes too severe.

A first ask from PerfTest is to add support for exclusive queues. A second ask is to handle publishing rates better - it's currently impossible to simulate 1 message per minute. Our specific use-case requires us to simulate 1 message every 10 minutes.

**Comment by acogoluegnes** [comment]
I need to experiment with the code, but the exclusive queue, producing to topic exchange should be doable without too much trouble. Publishing 1 message every 10 minutes is another story. Not sure the current rate limitation implementation would work for such a small rate. Moreover, we may need a random delay for each producer, to avoid a small publishing storm.
