### ISSUE TITLE
Command Options are duplicate

### ISSUE THREAD

**Issue by lxs137** [rabbitmq/rabbitmq-perf-test#85]
In PerfTest.java

`        options.addOption(new Option("T", "body-content-type",      true, "body content-type"));
`

`        options.addOption(new Option("T", "queue-pattern-to",       true, "sequence end for queue pattern (included)"));
`

**Comment by michaelklishin** [comment]
`queue-pattern-to` was introduced in 6b592582741406da6b1691244e536eb9a6ae909e and was never a part of a GA release, so we should change that one.

**Comment by lxs137** [comment]
But if I use "--body-content-type application/json", it will throw exception:
`Main thread caught exception: java.lang.NumberFormatException: For input string: "application/json"
java.lang.NumberFormatException: For input string: "application/json"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at com.rabbitmq.perf.PerfTest.intArg(PerfTest.java:357)
	at com.rabbitmq.perf.PerfTest.main(PerfTest.java:161)
	at com.rabbitmq.perf.PerfTest.main(PerfTest.java:252)`

**Comment by michaelklishin** [comment]
This is expected because the latter `-T` flag is an integer and it overrides the previous value.

**Comment by lxs137** [comment]
So I should use Release "2.0.0" instead of "2.1.0.M2" ?

**Comment by michaelklishin** [comment]
As the name suggests, 2.1.0.M2 is a preview release. If you don't need any of the improvements in it, I'd use 2.0. That said, this issue will be resolved in the next hour or so.

**Comment by lxs137** [comment]
I get it. Thanks!!

**Comment by acogoluegnes** [comment]
@michaelklishin Yes, makes sense to release a new milestone with this fix, I'll do it.

**Comment by michaelklishin** [comment]
@lxs137 please give 2.1.0.M4 a try.
