### ISSUE TITLE
PerfTestMulti test does not end as expected

### ISSUE THREAD

**Issue by andinod** [rabbitmq/rabbitmq-perf-test#95]
For the stable version 2.1.1 I found that is not working anymore for any json file configuration. Please if something have changed then update the documentation or review what could be the conflict, because the system just doesn't throw any error but stays still without showing any progress and doing nothing.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes that we have a certain amount of information to work with.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing and sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. OS/systemd logs, [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html), deployment tool logs, etc

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have a complete enough understanding of what's going on, a recommendation will be provided or a new issues with more context will be filed.

Thank you.

**Comment by michaelklishin** [comment]
Please be more specific than "not working any more".

**Comment by acogoluegnes** [comment]
@andinod Thanks for reporting. I tried the [very first example](https://github.com/rabbitmq/rabbitmq-perf-test/blob/master/html/README.md): the test does run, but it doesn't stop despite the time limit and doesn't produce any result file if ctrl-c'ed. Investigating.

**Comment by acogoluegnes** [comment]
@andinod 2.1.2 with the fix is available: https://bintray.com/rabbitmq/java-tools/perf-test/2.1.2. Thanks for reporting!

**Comment by andinod** [comment]
Thanks @acogoluegnes for taking your time to fix it. :-)
